# Generated by Django 3.1.4 on 2021-01-04 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordernumber', models.IntegerField()),
                ('date', models.DateField()),
                ('CPhonenum', models.FloatField(max_length=10)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='Namee',
        ),
        migrations.AddField(
            model_name='test',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='Height',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='SID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='Weight',
            field=models.FloatField(max_length=10),
        ),
    ]
