# Generated by Django 3.1.4 on 2021-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210104_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('MID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Mname', models.CharField(max_length=40)),
                ('MPrice', models.IntegerField(max_length=255)),
                ('Mcount', models.IntegerField(max_length=10)),
                ('LTime', models.IntegerField(max_length=100)),
                ('WLeft', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
