# Generated by Django 3.1.4 on 2021-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=100)),
                ('Namee', models.CharField(max_length=100)),
                ('Height', models.CharField(max_length=100)),
                ('Weight', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
